name: unidwell_finder
description: "Accommodation finder for university students."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  go_router: ^14.2.1
  url_strategy: ^0.2.0
  riverpod: ^2.5.1
  flutter_riverpod: ^2.5.1
  flutter_smart_dialog: ^4.9.7+8
  carousel_slider: ^4.2.1
  flutter_markdown: ^0.7.3
  intl: ^0.19.0
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  cloud_firestore: ^5.1.0
  faker: ^2.1.0
  fl_chart: ^0.68.0
  collection: ^1.18.0
  data_table_2: ^2.5.15
  image_picker: ^1.1.2
  firebase_storage: ^12.1.1
  http: ^1.2.2
  flutter_native_splash: ^2.4.1
  permission_handler: ^11.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  js: ^0.7.1
  pay_with_paystack: ^1.0.10
  url_launcher: ^6.3.0
  geolocator: ^12.0.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  flutter_launcher_icons: "^0.13.1"

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/fonts/
    - assets/images/


assets:
  - assets/fonts/
  - assets/images/
  - assets/docs/
fonts:
  - family: OpenSans
    fonts:
      - asset: assets/fonts/OpenSans-Regular.ttf
      - asset: assets/fonts/OpenSans-Bold.ttf
      - asset: assets/fonts/OpenSans-Light.ttf
  - family: Raleway
    fonts:
      - asset: assets/fonts/Raleway-Bold.ttf
      - asset: assets/fonts/Raleway-Regular.ttf
      - asset: assets/fonts/Raleway-Light.ttf



flutter_native_splash:
  color: "#ffffff"
  image: assets/images/splash.png
  image_web: assets/images/hostel_logo_white_t.png
  android: true
  ios: true
  web: true
  android_12:
#dart run flutter_native_splash:create

flutter_launcher_icons:
  android: "launcher_icon"
  ios: false
  image_path: "assets/images/icon.png"
  min_sdk_android: 21 # android min sdk min:16, default 21
  web:
    generate: true
    image_path: "assets/images/icon.png"
    background_color: "#hexcode"
    theme_color: "#hexcode"
#    flutter pub run flutter_launcher_icons